stages:
- name: test
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: echo 'mytest'
  - publishImageConfig:
      dockerfilePath: ./package/Dockerfile
      buildContext: .
      tag: michelia/fluentd:build2
      registry: index.docker.io
timeout: 60
