stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./package/Dockerfile
      buildContext: ./package
      tag: fluentd:${CICD_EXECUTION_SEQUENCE}
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
